ARG venv_python=3.12
FROM python:${venv_python}

LABEL Maintainer="PCGL Project"

USER root

RUN groupadd -r pcgl && useradd -rm pcgl -g pcgl

COPY app/ /app/

WORKDIR /app/
RUN chown -R pcgl:pcgl /app

RUN mkdir -p /permissions_engine
RUN chown -R pcgl:pcgl /permissions_engine

USER pcgl
